# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launcher_3x.ui'
#
# Created: Sat May 11 19:03:48 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_window_main(object):
    def setupUi(self, window_main):
        window_main.setObjectName(_fromUtf8("window_main"))
        window_main.resize(537, 476)
        window_main.setMouseTracking(True)
        window_main.setStyleSheet(_fromUtf8(""))
        self.widget_main = QtGui.QWidget(window_main)
        self.widget_main.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(122, 122, 122);"))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.gridLayout = QtGui.QGridLayout(self.widget_main)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_opacity = QtGui.QLabel(self.widget_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.label_opacity.setFont(font)
        self.label_opacity.setObjectName(_fromUtf8("label_opacity"))
        self.horizontalLayout_2.addWidget(self.label_opacity)
        self.slider_opacity = QtGui.QSlider(self.widget_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.slider_opacity.setFont(font)
        self.slider_opacity.setMinimum(40)
        self.slider_opacity.setMaximum(100)
        self.slider_opacity.setProperty("value", 100)
        self.slider_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.slider_opacity.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.slider_opacity.setTickInterval(5)
        self.slider_opacity.setObjectName(_fromUtf8("slider_opacity"))
        self.horizontalLayout_2.addWidget(self.slider_opacity)
        self.lcd_opacity = QtGui.QLCDNumber(self.widget_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.lcd_opacity.setFont(font)
        self.lcd_opacity.setSmallDecimalPoint(True)
        self.lcd_opacity.setNumDigits(3)
        self.lcd_opacity.setDigitCount(3)
        self.lcd_opacity.setProperty("value", 100.0)
        self.lcd_opacity.setProperty("intValue", 100)
        self.lcd_opacity.setObjectName(_fromUtf8("lcd_opacity"))
        self.horizontalLayout_2.addWidget(self.lcd_opacity)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton = QtGui.QPushButton(self.widget_main)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton.setStyleSheet(_fromUtf8("font: 75 10pt \"Segoe UI\";"))
        self.pushButton.setCheckable(True)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.button_selectall = QtGui.QPushButton(self.widget_main)
        self.button_selectall.setMinimumSize(QtCore.QSize(55, 25))
        self.button_selectall.setMaximumSize(QtCore.QSize(55, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_selectall.setFont(font)
        self.button_selectall.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"font: 8pt \"Segoe UI\";"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_selectall.setIcon(icon)
        self.button_selectall.setFlat(True)
        self.button_selectall.setObjectName(_fromUtf8("button_selectall"))
        self.horizontalLayout.addWidget(self.button_selectall)
        self.button_invert = QtGui.QPushButton(self.widget_main)
        self.button_invert.setMinimumSize(QtCore.QSize(55, 25))
        self.button_invert.setMaximumSize(QtCore.QSize(55, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_invert.setFont(font)
        self.button_invert.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"font: 8pt \"Segoe UI\";"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/inverse.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_invert.setIcon(icon1)
        self.button_invert.setFlat(True)
        self.button_invert.setObjectName(_fromUtf8("button_invert"))
        self.horizontalLayout.addWidget(self.button_invert)
        self.button_selectnone = QtGui.QPushButton(self.widget_main)
        self.button_selectnone.setMinimumSize(QtCore.QSize(55, 25))
        self.button_selectnone.setMaximumSize(QtCore.QSize(55, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_selectnone.setFont(font)
        self.button_selectnone.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);\n"
"font: 8pt \"Segoe UI\";"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/none.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_selectnone.setIcon(icon2)
        self.button_selectnone.setFlat(True)
        self.button_selectnone.setObjectName(_fromUtf8("button_selectnone"))
        self.horizontalLayout.addWidget(self.button_selectnone)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_saveedits = QtGui.QPushButton(self.widget_main)
        self.button_saveedits.setEnabled(False)
        self.button_saveedits.setMinimumSize(QtCore.QSize(65, 25))
        self.button_saveedits.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.button_saveedits.setFont(font)
        self.button_saveedits.setStyleSheet(_fromUtf8("font: 75 8pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);"))
        self.button_saveedits.setFlat(True)
        self.button_saveedits.setObjectName(_fromUtf8("button_saveedits"))
        self.horizontalLayout.addWidget(self.button_saveedits)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_addapp = QtGui.QPushButton(self.widget_main)
        self.button_addapp.setMinimumSize(QtCore.QSize(90, 25))
        self.button_addapp.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_addapp.setFont(font)
        self.button_addapp.setStyleSheet(_fromUtf8("color: rgb(11, 143, 55);\n"
"font: 8pt \"Segoe UI\";"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/addapp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_addapp.setIcon(icon3)
        self.button_addapp.setFlat(True)
        self.button_addapp.setObjectName(_fromUtf8("button_addapp"))
        self.horizontalLayout.addWidget(self.button_addapp)
        self.button_addgroup = QtGui.QPushButton(self.widget_main)
        self.button_addgroup.setMinimumSize(QtCore.QSize(90, 25))
        self.button_addgroup.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_addgroup.setFont(font)
        self.button_addgroup.setStyleSheet(_fromUtf8("color: rgb(11, 143, 55);\n"
"font: 8pt \"Segoe UI\";"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/addgroup.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_addgroup.setIcon(icon4)
        self.button_addgroup.setFlat(True)
        self.button_addgroup.setObjectName(_fromUtf8("button_addgroup"))
        self.horizontalLayout.addWidget(self.button_addgroup)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 3)
        self.button_launch = QtGui.QPushButton(self.widget_main)
        self.button_launch.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI 12"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_launch.setFont(font)
        self.button_launch.setMouseTracking(True)
        self.button_launch.setStyleSheet(_fromUtf8("font: 12pt \"Segoe UI\" bold;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 85, 0);"))
        self.button_launch.setObjectName(_fromUtf8("button_launch"))
        self.gridLayout.addWidget(self.button_launch, 4, 1, 1, 3)
        self.treeview_applist = QtGui.QTreeWidget(self.widget_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.treeview_applist.setFont(font)
        self.treeview_applist.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeview_applist.setStyleSheet(_fromUtf8(""))
        self.treeview_applist.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeview_applist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeview_applist.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeview_applist.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.treeview_applist.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeview_applist.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeview_applist.setRootIsDecorated(False)
        self.treeview_applist.setUniformRowHeights(True)
        self.treeview_applist.setItemsExpandable(False)
        self.treeview_applist.setAllColumnsShowFocus(True)
        self.treeview_applist.setExpandsOnDoubleClick(False)
        self.treeview_applist.setObjectName(_fromUtf8("treeview_applist"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        self.treeview_applist.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        self.treeview_applist.headerItem().setFont(1, font)
        self.gridLayout.addWidget(self.treeview_applist, 3, 2, 1, 1)
        self.treeview_grouplist = QtGui.QTreeWidget(self.widget_main)
        self.treeview_grouplist.setMinimumSize(QtCore.QSize(165, 0))
        self.treeview_grouplist.setMaximumSize(QtCore.QSize(165, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.treeview_grouplist.setFont(font)
        self.treeview_grouplist.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeview_grouplist.setStyleSheet(_fromUtf8(""))
        self.treeview_grouplist.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeview_grouplist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeview_grouplist.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeview_grouplist.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.treeview_grouplist.setAlternatingRowColors(True)
        self.treeview_grouplist.setTextElideMode(QtCore.Qt.ElideNone)
        self.treeview_grouplist.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeview_grouplist.setRootIsDecorated(False)
        self.treeview_grouplist.setUniformRowHeights(True)
        self.treeview_grouplist.setItemsExpandable(False)
        self.treeview_grouplist.setAllColumnsShowFocus(True)
        self.treeview_grouplist.setExpandsOnDoubleClick(False)
        self.treeview_grouplist.setObjectName(_fromUtf8("treeview_grouplist"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        self.treeview_grouplist.headerItem().setFont(0, font)
        self.gridLayout.addWidget(self.treeview_grouplist, 3, 3, 1, 1)
        window_main.setCentralWidget(self.widget_main)
        self.menuBar = QtGui.QMenuBar(window_main)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menuFile.setFont(font)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menuView.setFont(font)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        window_main.setMenuBar(self.menuBar)
        self.menu_aboutqt = QtGui.QAction(window_main)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Qt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_aboutqt.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_aboutqt.setFont(font)
        self.menu_aboutqt.setObjectName(_fromUtf8("menu_aboutqt"))
        self.menu_exit = QtGui.QAction(window_main)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/start-here.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_exit.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_exit.setFont(font)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.menu_dbdesign = QtGui.QAction(window_main)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_dbdesign.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_dbdesign.setFont(font)
        self.menu_dbdesign.setObjectName(_fromUtf8("menu_dbdesign"))
        self.menu_about = QtGui.QAction(window_main)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/help-contents.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_about.setIcon(icon8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_about.setFont(font)
        self.menu_about.setObjectName(_fromUtf8("menu_about"))
        self.menu_selectallbydefault = QtGui.QAction(window_main)
        self.menu_selectallbydefault.setCheckable(True)
        self.menu_selectallbydefault.setChecked(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_selectallbydefault.setFont(font)
        self.menu_selectallbydefault.setObjectName(_fromUtf8("menu_selectallbydefault"))
        self.menu_startatboot = QtGui.QAction(window_main)
        self.menu_startatboot.setCheckable(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_startatboot.setFont(font)
        self.menu_startatboot.setObjectName(_fromUtf8("menu_startatboot"))
        self.menu_exportdatabase = QtGui.QAction(window_main)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/022.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_exportdatabase.setIcon(icon9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_exportdatabase.setFont(font)
        self.menu_exportdatabase.setObjectName(_fromUtf8("menu_exportdatabase"))
        self.menu_importdatabase = QtGui.QAction(window_main)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/03.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_importdatabase.setIcon(icon10)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_importdatabase.setFont(font)
        self.menu_importdatabase.setObjectName(_fromUtf8("menu_importdatabase"))
        self.menu_whatsnew = QtGui.QAction(window_main)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/changelog.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_whatsnew.setIcon(icon11)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_whatsnew.setFont(font)
        self.menu_whatsnew.setObjectName(_fromUtf8("menu_whatsnew"))
        self.menu_hideonfocusloss = QtGui.QAction(window_main)
        self.menu_hideonfocusloss.setCheckable(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_hideonfocusloss.setFont(font)
        self.menu_hideonfocusloss.setObjectName(_fromUtf8("menu_hideonfocusloss"))
        self.menu_wipealldata = QtGui.QAction(window_main)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/dialog-warning.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_wipealldata.setIcon(icon12)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_wipealldata.setFont(font)
        self.menu_wipealldata.setObjectName(_fromUtf8("menu_wipealldata"))
        self.menu_enablekeyboardshortcut = QtGui.QAction(window_main)
        self.menu_enablekeyboardshortcut.setCheckable(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_enablekeyboardshortcut.setFont(font)
        self.menu_enablekeyboardshortcut.setObjectName(_fromUtf8("menu_enablekeyboardshortcut"))
        self.menu_savewindowsize = QtGui.QAction(window_main)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/geometry.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_savewindowsize.setIcon(icon13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_savewindowsize.setFont(font)
        self.menu_savewindowsize.setObjectName(_fromUtf8("menu_savewindowsize"))
        self.menu_setwindowopacity = QtGui.QAction(window_main)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/opacity.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_setwindowopacity.setIcon(icon14)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.menu_setwindowopacity.setFont(font)
        self.menu_setwindowopacity.setObjectName(_fromUtf8("menu_setwindowopacity"))
        self.menu_findreplace = QtGui.QAction(window_main)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/find-replace.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_findreplace.setIcon(icon15)
        self.menu_findreplace.setObjectName(_fromUtf8("menu_findreplace"))
        self.menuHelp.addAction(self.menu_about)
        self.menuHelp.addAction(self.menu_dbdesign)
        self.menuHelp.addAction(self.menu_whatsnew)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.menu_wipealldata)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.menu_aboutqt)
        self.menuFile.addAction(self.menu_importdatabase)
        self.menuFile.addAction(self.menu_exportdatabase)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menu_savewindowsize)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menu_exit)
        self.menuView.addAction(self.menu_selectallbydefault)
        self.menuView.addAction(self.menu_hideonfocusloss)
        self.menuView.addAction(self.menu_enablekeyboardshortcut)
        self.menuView.addAction(self.menu_startatboot)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menu_findreplace)
        self.menuView.addAction(self.menu_setwindowopacity)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(window_main)
        QtCore.QObject.connect(self.slider_opacity, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcd_opacity.display)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.menuBar.setVisible)
        QtCore.QMetaObject.connectSlotsByName(window_main)
        window_main.setTabOrder(self.button_selectall, self.button_invert)
        window_main.setTabOrder(self.button_invert, self.button_selectnone)
        window_main.setTabOrder(self.button_selectnone, self.button_addgroup)
        window_main.setTabOrder(self.button_addgroup, self.button_saveedits)
        window_main.setTabOrder(self.button_saveedits, self.slider_opacity)

    def retranslateUi(self, window_main):
        window_main.setWindowTitle(_translate("window_main", "Launcher_3x", None))
        self.label_opacity.setText(_translate("window_main", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#636363;\">Opacity</span></p></body></html>", None))
        self.slider_opacity.setToolTip(_translate("window_main", "Opacity", None))
        self.slider_opacity.setStatusTip(_translate("window_main", "Opacity", None))
        self.slider_opacity.setWhatsThis(_translate("window_main", "Opacity Level", None))
        self.pushButton.setText(_translate("window_main", "...", None))
        self.button_selectall.setText(_translate("window_main", "ALL", None))
        self.button_invert.setText(_translate("window_main", "INV", None))
        self.button_selectnone.setText(_translate("window_main", "NON", None))
        self.button_saveedits.setText(_translate("window_main", "*   SAVE   *", None))
        self.button_addapp.setText(_translate("window_main", "Add App", None))
        self.button_addgroup.setText(_translate("window_main", "Add Group", None))
        self.button_launch.setText(_translate("window_main", "- LAUNCH -", None))
        self.treeview_applist.headerItem().setText(0, _translate("window_main", "App Name", None))
        self.treeview_applist.headerItem().setText(1, _translate("window_main", "App Path", None))
        self.treeview_grouplist.headerItem().setText(0, _translate("window_main", "App Groups", None))
        self.menuHelp.setTitle(_translate("window_main", "Help", None))
        self.menuFile.setTitle(_translate("window_main", "File", None))
        self.menuView.setTitle(_translate("window_main", "Tools", None))
        self.menu_aboutqt.setText(_translate("window_main", "About Qt", None))
        self.menu_exit.setText(_translate("window_main", "Exit", None))
        self.menu_dbdesign.setText(_translate("window_main", "DB Schema", None))
        self.menu_about.setText(_translate("window_main", "About", None))
        self.menu_selectallbydefault.setText(_translate("window_main", "Select All by Default", None))
        self.menu_startatboot.setText(_translate("window_main", "Start at Boot", None))
        self.menu_exportdatabase.setText(_translate("window_main", "Export Database", None))
        self.menu_importdatabase.setText(_translate("window_main", "Import Database", None))
        self.menu_whatsnew.setText(_translate("window_main", "Release Notes", None))
        self.menu_hideonfocusloss.setText(_translate("window_main", "Hide Window on Focus Loss", None))
        self.menu_wipealldata.setText(_translate("window_main", "Wipe All Data!", None))
        self.menu_enablekeyboardshortcut.setText(_translate("window_main", "Enable Keyboard Shortcuts", None))
        self.menu_savewindowsize.setText(_translate("window_main", "Save Geometry", None))
        self.menu_setwindowopacity.setText(_translate("window_main", "Window Opacity", None))
        self.menu_findreplace.setText(_translate("window_main", "Find/Replace", None))

import launcher_3x_rc

class window_main(QtGui.QMainWindow, Ui_window_main):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

